import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quotes.md",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="google-site-verification"
        content="RM-JfmX5StMSXddp2ggzS1GyoTt6J0gSkqC025emL6U"
      />
      <body className={`${sora.className}`}>{children}</body>
    </html>
  );
}
